[tools]
"github:microsoft/apm" = { version = "v0.23.1", bin = "apm" }
"github:eljulians/skillfile" = { version = "v1.7.1", bin = "skillfile" }
"uv" = "0.11.26"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.12.4"

[tasks.update-agents]
description = "Update agents to the latest version"
run = [
    "cd {{config_root}}/ai && apm install --trust-transitive-mcp --force",
    "cd {{config_root}}/agents && apm install --trust-transitive-mcp --force",
    "apm install --global --trust-transitive-mcp --force",
]

[settings]
lockfile = true