[tools]
"github:microsoft/apm" = { version = "v0.26.0", bin = "apm" }
"github:eljulians/skillfile" = { version = "v1.9.0", bin = "skillfile" }
"uv" = "0.11.30"

[tasks.update-agents]
description = "Update agents to the latest version"
run = [
    "cd {{config_root}}/ai && apm install --trust-transitive-mcp --force",
    "cd {{config_root}}/agents && apm install --trust-transitive-mcp --force",
    "apm install --global --trust-transitive-mcp --force",
]

[settings]
lockfile = true