[tools]
fzf = "latest"
"uv" = "latest"
jq = "latest"
yq = "latest"
sops = "latest"
age = "latest"
"npm:@bradygaster/squad-cli" = "latest"
"npm:@github/copilot" = "latest"
"dotnet:graphify-dotnet" = "latest"
biome = "latest"
"npm:@opengsd/gsd-core" = "latest"

[hooks]
postinstall = { task = "gh-extensions" }

[tasks.gh-mcp]
run = "gh extensions install shuymn/gh-mcp"

[tasks.gh-extensions]
run.tasks = ["gh-mcp"]

[tasks.mcp-gateway]
run = [
    "echo {{ cwd }}",
    # todo make this better for environment variables
    "docker run --name mcphub -p 3000:3000 -e SLACK_CLIENT_ID -e CONTEXT7_API_KEY -e ADMIN_PASSWORD -v ./mcp_settings.json:/app/mcp_settings.json -v ./servers.json:/app/servers.json samanhappy/mcphub"
]
dir = "{{ env.HOME | default(value=env.USERPROFILE) }}/dotfiles/mcphub"
env = { _.file = { path = "~/dotfiles/mcphub/secrets.sops.json", redact = true } }

[settings]
idiomatic_version_file_enable_tools = ["dotnet"]
