#:schema https://fnox.jdx.dev/schema.json
# default_provider = "age"

# Currently not supported see https://github.com/jdx/fnox/pull/818
# import = ["~/.config/fnox/config.local.toml"]

[daemon]
enabled = true
idle_timeout = "8h"

[secrets]
